name: Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  RISCV: /opt/riscv

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: veryl-lang/setup-veryl@v1
    - run: make check

  test:
    runs-on: ubuntu-22.04
    container:
      image: sardonyx30/veryl-riscv-toolchain:latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-riscv-tests
        path: ./core/tests/share
    - run: make test
