name: Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  RISCV: /opt/riscv

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: veryl-lang/setup-veryl@v1
    - run: make check

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: veryl-lang/setup-veryl@v1
    - uses: veryl-lang/setup-verilator@v1

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-riscv-toolchain
        path: /opt/riscv
    - name: Install RISC-V toolchain
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          ca-certificates ccache mold \
          git autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev \
          gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev

        git clone https://github.com/riscv/riscv-gnu-toolchain && cd riscv-gnu-toolchain && \
          ./configure --prefix=${{ env.RISCV }} && make newlib -j"$(nproc)"
        echo "${{ env.RISCV }}/bin" >> $GITHUB_PATH

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-riscv-tests
        path: ./core/tests/share
    - run: make test
