name: Lint and Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  RISCV: /opt/riscv

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: veryl-lang/setup-veryl@v1
    - run: make check

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: veryl-lang/setup-veryl@v1
    - uses: veryl-lang/setup-verilator@v1

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-riscv-toolchain
        path: /opt/riscv
    - name: Install RISC-V toolchain
      run: |
        wget -q https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2025.01.17/riscv64-elf-ubuntu-22.04-gcc-nightly-2025.01.17-nightly.tar.xz
        sudo mkdir -p ${{ env.RISCV }}
        sudo tar -xvf riscv64-elf-ubuntu-22.04-gcc-nightly-2025.01.17-nightly.tar.xz -C /opt
        echo "${{ env.RISCV }}/bin" >> $GITHUB_PATH

    - name: Install RISC-V ISA simulator
      run: |
        sudo apt-get install -y --no-install-recommends device-tree-compiler
        git clone https://github.com/riscv/riscv-isa-sim.git && \
          cd riscv-isa-sim && \
          mkdir build && \
          cd build && \
          ../configure --prefix=$RISCV && \
          make -j"$(nproc)" && \
          make install

    # riscv proxy kernel
    - name: Install RISC-V proxy kernel
      run: |
        sudo apt-get install -y --no-install-recommends device-tree-compiler
        git clone https://github.com/riscv/riscv-pk && \
        cd riscv-pk && \
        mkdir build && \
        cd build && \
        ../configure --prefix=$RISCV --host=riscv64-unknown-elf && \
        make -j"$(nproc)" && \
        make install

    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-riscv-tests
        path: ./core/tests/share
    - run: make test
